# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master



stages:
  - stage: BuildAndCreateImage
    pool:
      vmImage: ubuntu-latest
    jobs:
    - job:
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
      - task: Docker@2
        inputs:
          containerRegistry: 'dockerhub-connection'
          repository: 'test-dotnet:$(Build.BuildId)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: 

      

