apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-webapp
spec:
  selector:
    matchLabels:
      app: dotnet-webapp
  replicas: 5
  template:
    metadata:
      labels:
        app: dotnet-webapp
    spec:
      containers:
      - name: dotnet-webapp
        image: biswajit59/dotnetwebapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  selector:
    app: dotnet-webapp
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  